-- ห้องโอบรัก (Ob Rak) — Supabase schema
-- รันไฟล์นี้ครั้งเดียวใน Supabase Dashboard > SQL Editor

begin;

create extension if not exists pgcrypto;
create schema if not exists private;
revoke all on schema private from public;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  student_id text unique,
  name text not null,
  email text not null,
  role text not null default 'student' check (role in ('student', 'counselor', 'admin')),
  consent_privacy boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.counselors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references public.profiles(id) on delete set null,
  display_name text not null,
  title text not null,
  specialties jsonb not null default '[]'::jsonb,
  bio text not null default '',
  meeting_modes jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  counselor_id uuid not null references public.counselors(id) on delete cascade,
  weekday integer not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_minutes integer not null default 45 check (slot_minutes between 15 and 180),
  created_at timestamptz not null default now(),
  constraint availability_time_check check (end_time > start_time),
  constraint availability_unique unique (counselor_id, weekday, start_time, end_time)
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  counselor_id uuid not null references public.counselors(id) on delete restrict,
  appointment_date date not null,
  appointment_time time not null,
  duration_minutes integer not null default 45 check (duration_minutes between 15 and 180),
  mode text not null,
  topic text not null,
  note text not null default '',
  risk_level text not null default 'normal' check (risk_level in ('normal', 'concern', 'urgent', 'immediate')),
  status text not null default 'confirmed' check (status in ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists appointments_active_slot_unique
  on public.appointments (counselor_id, appointment_date, appointment_time)
  where status in ('pending', 'confirmed');

create index if not exists appointments_user_idx on public.appointments(user_id, appointment_date);
create index if not exists appointments_counselor_idx on public.appointments(counselor_id, appointment_date);

create table if not exists public.mood_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  mood text not null,
  stress integer not null check (stress between 0 and 10),
  energy integer not null check (energy between 0 and 10),
  note text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists mood_entries_user_created_idx on public.mood_entries(user_id, created_at desc);

create table if not exists public.assessment_results (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  assessment_type text not null,
  score integer not null check (score >= 0),
  max_score integer not null check (max_score > 0 and score <= max_score),
  level text not null,
  answers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists assessment_results_user_created_idx on public.assessment_results(user_id, created_at desc);

create table if not exists public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references public.profiles(id) on delete cascade,
  title text not null,
  content text not null,
  mood text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists journal_entries_user_created_idx on public.journal_entries(user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Auth profile trigger
-- Role is always forced to student here. Do not trust user_metadata for roles.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, student_id, name, email, role, consent_privacy)
  values (
    new.id,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'student_id', '')), ''),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1)),
    coalesce(new.email, ''),
    'student',
    coalesce((new.raw_user_meta_data ->> 'consent_privacy')::boolean, false)
  );
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_updated_at() from public;

drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at
  before update on public.appointments
  for each row execute procedure public.set_updated_at();

drop trigger if exists journal_entries_set_updated_at on public.journal_entries;
create trigger journal_entries_set_updated_at
  before update on public.journal_entries
  for each row execute procedure public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Private authorization helpers used by RLS
-- ---------------------------------------------------------------------------

create or replace function private.current_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.role
  from public.profiles p
  where p.id = (select auth.uid())
$$;

create or replace function private.can_access_appointment(p_user_id uuid, p_counselor_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select auth.uid()) = p_user_id
    or private.current_role() = 'admin'
    or exists (
      select 1
      from public.counselors c
      where c.id = p_counselor_id
        and c.user_id = (select auth.uid())
    )
$$;

create or replace function private.can_view_profile(p_profile_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select auth.uid()) = p_profile_id
    or private.current_role() = 'admin'
    or exists (
      select 1
      from public.appointments a
      join public.counselors c on c.id = a.counselor_id
      where a.user_id = p_profile_id
        and c.user_id = (select auth.uid())
    )
$$;

revoke all on function private.current_role() from public;
revoke all on function private.can_access_appointment(uuid, uuid) from public;
revoke all on function private.can_view_profile(uuid) from public;
grant usage on schema private to authenticated;
grant execute on function private.current_role() to authenticated;
grant execute on function private.can_access_appointment(uuid, uuid) to authenticated;
grant execute on function private.can_view_profile(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.counselors enable row level security;
alter table public.availability enable row level security;
alter table public.appointments enable row level security;
alter table public.mood_entries enable row level security;
alter table public.assessment_results enable row level security;
alter table public.journal_entries enable row level security;

-- Profiles: users see themselves; assigned counselors see their students; admins see all.
drop policy if exists profiles_select_authorized on public.profiles;
create policy profiles_select_authorized
  on public.profiles for select
  to authenticated
  using ((select private.can_view_profile(id)));

-- Public counselor directory and availability.
drop policy if exists counselors_public_select on public.counselors;
create policy counselors_public_select
  on public.counselors for select
  to anon, authenticated
  using (active = true);

drop policy if exists counselors_staff_select on public.counselors;
create policy counselors_staff_select
  on public.counselors for select
  to authenticated
  using ((select private.current_role()) in ('counselor', 'admin'));

drop policy if exists availability_public_select on public.availability;
create policy availability_public_select
  on public.availability for select
  to anon, authenticated
  using (exists (
    select 1 from public.counselors c
    where c.id = availability.counselor_id and c.active = true
  ));

-- Appointment rows are visible only to the student, assigned counselor, or admin.
drop policy if exists appointments_select_authorized on public.appointments;
create policy appointments_select_authorized
  on public.appointments for select
  to authenticated
  using ((select private.can_access_appointment(user_id, counselor_id)));

-- Personal wellbeing data.
drop policy if exists moods_select_own on public.mood_entries;
create policy moods_select_own
  on public.mood_entries for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists moods_insert_own on public.mood_entries;
create policy moods_insert_own
  on public.mood_entries for insert
  to authenticated
  with check ((select auth.uid()) = user_id and (select private.current_role()) = 'student');

drop policy if exists assessments_select_own on public.assessment_results;
create policy assessments_select_own
  on public.assessment_results for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists assessments_insert_own on public.assessment_results;
create policy assessments_insert_own
  on public.assessment_results for insert
  to authenticated
  with check ((select auth.uid()) = user_id and (select private.current_role()) = 'student');

drop policy if exists journals_select_own on public.journal_entries;
create policy journals_select_own
  on public.journal_entries for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists journals_insert_own on public.journal_entries;
create policy journals_insert_own
  on public.journal_entries for insert
  to authenticated
  with check ((select auth.uid()) = user_id and (select private.current_role()) = 'student');

drop policy if exists journals_delete_own on public.journal_entries;
create policy journals_delete_own
  on public.journal_entries for delete
  to authenticated
  using ((select auth.uid()) = user_id and (select private.current_role()) = 'student');

-- Remove broad table privileges and grant only what the browser app needs.
revoke all on public.profiles from anon, authenticated;
revoke all on public.counselors from anon, authenticated;
revoke all on public.availability from anon, authenticated;
revoke all on public.appointments from anon, authenticated;
revoke all on public.mood_entries from anon, authenticated;
revoke all on public.assessment_results from anon, authenticated;
revoke all on public.journal_entries from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.counselors to anon, authenticated;
grant select on public.availability to anon, authenticated;
grant select on public.appointments to authenticated;
grant select, insert on public.mood_entries to authenticated;
grant select, insert on public.assessment_results to authenticated;
grant select, insert, delete on public.journal_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Booking RPCs: all writes to appointments go through these functions.
-- ---------------------------------------------------------------------------

create or replace function public.get_available_slots(
  p_counselor_id uuid,
  p_date date
)
returns table(slot_time text, duration integer)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_date is null or p_date < current_date or p_date > current_date + 60 then
    return;
  end if;

  return query
  select
    to_char(gs.slot_ts, 'HH24:MI') as slot_time,
    a.slot_minutes as duration
  from public.availability a
  join public.counselors c on c.id = a.counselor_id and c.active = true
  cross join lateral generate_series(
    p_date + a.start_time,
    p_date + a.end_time - make_interval(mins => a.slot_minutes),
    make_interval(mins => a.slot_minutes)
  ) as gs(slot_ts)
  where a.counselor_id = p_counselor_id
    and a.weekday = extract(dow from p_date)::integer
    and not exists (
      select 1
      from public.appointments ap
      where ap.counselor_id = p_counselor_id
        and ap.appointment_date = p_date
        and ap.appointment_time = gs.slot_ts::time
        and ap.status in ('pending', 'confirmed')
    )
  order by gs.slot_ts;
end;
$$;

revoke all on function public.get_available_slots(uuid, date) from public;
grant execute on function public.get_available_slots(uuid, date) to anon, authenticated;

create or replace function public.book_appointment(
  p_counselor_id uuid,
  p_date date,
  p_time time,
  p_mode text,
  p_topic text,
  p_note text default '',
  p_risk_level text default 'normal'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_duration integer;
  v_id uuid;
begin
  if v_user_id is null then
    raise exception 'กรุณาเข้าสู่ระบบก่อนจองนัด';
  end if;
  if private.current_role() <> 'student' then
    raise exception 'การจองนัดใช้สำหรับบัญชีนักศึกษา';
  end if;
  if p_risk_level = 'immediate' then
    raise exception 'ตอนนี้ควรติดต่อความช่วยเหลือเร่งด่วนก่อนการรอนัดหมาย';
  end if;
  if p_risk_level not in ('normal', 'concern', 'urgent', 'immediate') then
    raise exception 'ระดับการคัดกรองไม่ถูกต้อง';
  end if;
  if p_date < current_date or p_date > current_date + 60 then
    raise exception 'วันที่นัดหมายไม่อยู่ในช่วงที่เปิดจอง';
  end if;
  if coalesce(trim(p_mode), '') = '' or coalesce(trim(p_topic), '') = '' then
    raise exception 'กรอกข้อมูลการนัดหมายให้ครบ';
  end if;
  if not exists (
    select 1 from public.counselors c
    where c.id = p_counselor_id
      and c.active = true
      and c.meeting_modes ? p_mode
  ) then
    raise exception 'ผู้ให้คำปรึกษาหรือรูปแบบการพูดคุยไม่ถูกต้อง';
  end if;

  select s.duration into v_duration
  from public.get_available_slots(p_counselor_id, p_date) s
  where s.slot_time = to_char(current_date + p_time, 'HH24:MI')
  limit 1;

  if v_duration is null then
    raise exception 'ช่วงเวลานี้ไม่ว่างแล้ว กรุณาเลือกเวลาใหม่';
  end if;

  insert into public.appointments (
    user_id, counselor_id, appointment_date, appointment_time,
    duration_minutes, mode, topic, note, risk_level, status
  ) values (
    v_user_id, p_counselor_id, p_date, p_time,
    v_duration, trim(p_mode), trim(p_topic), left(coalesce(p_note, ''), 1200),
    coalesce(nullif(p_risk_level, ''), 'normal'), 'confirmed'
  ) returning id into v_id;

  return v_id;
exception
  when unique_violation then
    raise exception 'ช่วงเวลานี้มีผู้จองแล้ว กรุณาเลือกเวลาใหม่';
end;
$$;

revoke all on function public.book_appointment(uuid, date, time, text, text, text, text) from public;
grant execute on function public.book_appointment(uuid, date, time, text, text, text, text) to authenticated;

create or replace function public.reschedule_appointment(
  p_appointment_id uuid,
  p_date date,
  p_time time
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_counselor_id uuid;
  v_duration integer;
begin
  select a.counselor_id into v_counselor_id
  from public.appointments a
  where a.id = p_appointment_id
    and a.user_id = v_user_id
    and a.status in ('pending', 'confirmed');

  if v_counselor_id is null then
    raise exception 'ไม่พบนัดหมายของคุณหรือไม่สามารถเลื่อนนัดนี้ได้';
  end if;
  if p_date < current_date or p_date > current_date + 60 then
    raise exception 'วันที่นัดหมายไม่อยู่ในช่วงที่เปิดจอง';
  end if;

  select s.duration into v_duration
  from public.get_available_slots(v_counselor_id, p_date) s
  where s.slot_time = to_char(current_date + p_time, 'HH24:MI')
  limit 1;

  if v_duration is null then
    raise exception 'ช่วงเวลานี้ไม่ว่างแล้ว';
  end if;

  update public.appointments
  set appointment_date = p_date,
      appointment_time = p_time,
      duration_minutes = v_duration
  where id = p_appointment_id;
exception
  when unique_violation then
    raise exception 'ช่วงเวลานี้มีผู้จองแล้ว';
end;
$$;

revoke all on function public.reschedule_appointment(uuid, date, time) from public;
grant execute on function public.reschedule_appointment(uuid, date, time) to authenticated;

create or replace function public.cancel_appointment(p_appointment_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_row public.appointments%rowtype;
begin
  select * into v_row from public.appointments where id = p_appointment_id;
  if v_row.id is null then
    raise exception 'ไม่พบนัดหมาย';
  end if;

  if not private.can_access_appointment(v_row.user_id, v_row.counselor_id) then
    raise exception 'ไม่มีสิทธิ์ยกเลิกนัดนี้';
  end if;

  if v_row.status not in ('pending', 'confirmed') then
    raise exception 'นัดหมายนี้ไม่สามารถยกเลิกได้';
  end if;

  update public.appointments
  set status = 'cancelled'
  where id = p_appointment_id;
end;
$$;

revoke all on function public.cancel_appointment(uuid) from public;
grant execute on function public.cancel_appointment(uuid) to authenticated;

create or replace function public.update_appointment_status(
  p_appointment_id uuid,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.appointments%rowtype;
  v_role text := private.current_role();
begin
  if p_status not in ('confirmed', 'completed', 'cancelled', 'no_show') then
    raise exception 'สถานะไม่ถูกต้อง';
  end if;

  select * into v_row from public.appointments where id = p_appointment_id;
  if v_row.id is null then
    raise exception 'ไม่พบนัดหมาย';
  end if;

  if v_role = 'admin' then
    null;
  elsif v_role = 'counselor' and exists (
    select 1 from public.counselors c
    where c.id = v_row.counselor_id and c.user_id = (select auth.uid())
  ) then
    null;
  else
    raise exception 'ไม่มีสิทธิ์แก้ไขสถานะนัดนี้';
  end if;

  update public.appointments
  set status = p_status
  where id = p_appointment_id;
end;
$$;

revoke all on function public.update_appointment_status(uuid, text) from public;
grant execute on function public.update_appointment_status(uuid, text) to authenticated;

create or replace function public.admin_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if private.current_role() <> 'admin' then
    raise exception 'ไม่มีสิทธิ์ดูข้อมูลส่วนนี้';
  end if;

  select jsonb_build_object(
    'students', (select count(*) from public.profiles where role = 'student'),
    'upcoming', (select count(*) from public.appointments where status in ('pending', 'confirmed') and appointment_date >= current_date),
    'completed', (select count(*) from public.appointments where status = 'completed'),
    'assessments', (select count(*) from public.assessment_results),
    'topics', coalesce((
      select jsonb_agg(jsonb_build_object('topic', topic, 'count', total) order by total desc)
      from (
        select topic, count(*) as total
        from public.appointments
        group by topic
        order by total desc
        limit 5
      ) t
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.admin_stats() from public;
grant execute on function public.admin_stats() to authenticated;

-- ---------------------------------------------------------------------------
-- Demo counselor catalog and weekly availability
-- ---------------------------------------------------------------------------

insert into public.counselors (
  id, display_name, title, specialties, bio, meeting_modes, active
) values
(
  '11111111-1111-4111-8111-111111111111',
  'อาจารย์พยาบาลจิตเวช (ตัวอย่าง)',
  'อาจารย์พยาบาลสุขภาพจิตและจิตเวช',
  '["ความเครียดจากการเรียน","ก่อนขึ้นฝึก","การสื่อสารกับผู้ป่วย","ภาวะหมดไฟ"]'::jsonb,
  'ให้คำปรึกษาเบื้องต้นแก่นักศึกษาพยาบาล โดยเน้นการรับฟังอย่างไม่ตัดสิน',
  '["พบที่ห้อง","วิดีโอคอล","โทรศัพท์"]'::jsonb,
  true
),
(
  '22222222-2222-4222-8222-222222222222',
  'นักจิตวิทยาการปรึกษา (ตัวอย่าง)',
  'นักจิตวิทยาการปรึกษา',
  '["ความวิตกกังวล","ความสัมพันธ์","การนอนหลับ","การปรับตัว"]'::jsonb,
  'ให้คำปรึกษาด้านอารมณ์ ความคิด และการปรับตัวในชีวิตมหาวิทยาลัย',
  '["วิดีโอคอล","โทรศัพท์","แชตข้อความ"]'::jsonb,
  true
)
on conflict (id) do update set
  display_name = excluded.display_name,
  title = excluded.title,
  specialties = excluded.specialties,
  bio = excluded.bio,
  meeting_modes = excluded.meeting_modes,
  active = excluded.active;

insert into public.availability (counselor_id, weekday, start_time, end_time, slot_minutes)
select '11111111-1111-4111-8111-111111111111'::uuid, weekday, start_time, end_time, 45
from (values
  (1, '09:00'::time, '12:00'::time), (1, '13:00'::time, '16:00'::time),
  (2, '09:00'::time, '12:00'::time), (2, '13:00'::time, '16:00'::time),
  (3, '09:00'::time, '12:00'::time), (3, '13:00'::time, '16:00'::time),
  (4, '09:00'::time, '12:00'::time), (4, '13:00'::time, '16:00'::time),
  (5, '09:00'::time, '12:00'::time), (5, '13:00'::time, '16:00'::time)
) as v(weekday, start_time, end_time)
on conflict do nothing;

insert into public.availability (counselor_id, weekday, start_time, end_time, slot_minutes)
select '22222222-2222-4222-8222-222222222222'::uuid, weekday, start_time, end_time, 45
from (values
  (2, '10:00'::time, '12:15'::time), (2, '13:30'::time, '17:15'::time),
  (4, '10:00'::time, '12:15'::time), (4, '13:30'::time, '17:15'::time),
  (5, '10:00'::time, '12:15'::time), (5, '13:30'::time, '17:15'::time)
) as v(weekday, start_time, end_time)
on conflict do nothing;

commit;
